/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import CustomShaderMaterial from 'three-custom-shader-material/vanilla'
import * as THREE from 'three'
import { useControls, button } from 'leva'

import cowPatternVertexShader from './shaders/cow-pattern/vertex.glsl'
import cowPatternFragmentShader from './shaders/cow-pattern/fragment.glsl'


export default function Cow(props) {
    const cowMaterial = useMemo(() => {
        return new CustomShaderMaterial({
            baseMaterial: THREE.MeshStandardMaterial,
            vertexShader: cowPatternVertexShader,
            fragmentShader: cowPatternFragmentShader,
            uniforms: {
                uStepValue: new THREE.Uniform(0.09),
                uPatternSize: new THREE.Uniform(0.68),
                uSmoothValue: new THREE.Uniform(0.06),
                uSeed: new THREE.Uniform(new THREE.Vector3(0, 0, 0))
            },
            roughness: 0.5
        })
    }, [])

    let index = 0
    // predefined seed presets
    const seeds = [
        new THREE.Vector3(0, 0, 0),
        new THREE.Vector3(7, 7, 7),
        new THREE.Vector3(13, 13, 13),
        new THREE.Vector3(16, 16, 16),
        new THREE.Vector3(2, 2, 2),
        new THREE.Vector3(10, 20, 30)
    ]

    const { uStepValue, uPatternSize, uSmoothValue } = useControls({
        uStepValue: {
            value: 0.09,
            min: -1,
            max: 1,
            step: 0.01
        },
        uPatternSize: {
            value: 0.68,
            min: 0,
            max: 10.0,
            step: 0.01
        },
        uSmoothValue: {
            value: 0.06,
            min: 0,
            max: 0.2,
            step: 0.001
        },

        // set of 6 patterns
        "Change pattern": button(() => {
            index = (index + 1) % seeds.length
            cowMaterial.uniforms.uSeed.value.copy(seeds[index])
        })
    })

    useEffect(() => {
        cowMaterial.uniforms.uStepValue.value = uStepValue
        cowMaterial.uniforms.uPatternSize.value = uPatternSize
        cowMaterial.uniforms.uSmoothValue.value = uSmoothValue
    }, [uStepValue, uPatternSize, uSmoothValue, cowMaterial])

    const { nodes, materials } = useGLTF('./cow/cow.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                name="body"
                castShadow
                receiveShadow
                geometry={nodes.body.geometry}
                material={cowMaterial}
            />
            <mesh
                name="face_leg"
                castShadow
                receiveShadow
                geometry={nodes.face_leg.geometry}
                material={materials.cow}
                position={[0, 0.884, 0.779]}
                scale={0.97}
            />
            <group name="other_part" position={[0.353, 1.633, 0.745]} rotation={[0, 0, -0.361]}>
                <mesh
                    name="Cube047"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube047.geometry}
                    material={materials['Material.001']}
                />
                <mesh
                    name="Cube047_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube047_1.geometry}
                    material={materials['Material.003']}
                />
                <mesh
                    name="Cube047_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube047_2.geometry}
                    material={materials['Material.002']}
                />
            </group>
        </group>
    )
}

useGLTF.preload('.cow/cow.glb')
